server:
  port: 8080

spring:
  application:
    name: CoffeeClient
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/CoffeeOrdersDB
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver