#spring:
#  jpa:
##    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    show-sql: true
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.MySQLDialect
#  datasource:
##    url: jdbc:mysql://localhost:3308
#    url: jdbc:mysql://localhost:3307/CoffeeOrdersDB
##    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: password
server:
  port: 8080

spring:
  application:
    name: CoffeeClient